version: '3.8'

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_DATABASE: pokedex_db
      MYSQL_ROOT_PASSWORD: secret_password
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    user: "1000:1000"
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - DATABASE_URL=mysql://root:secret_password@db/pokedex_db
    depends_on:
      - db
